#!/usr/bin/env bash

help_message="\
usage: print-colors [options]
  options:
    -h, --help                   Shows this help message
    -b, --bit                    Specify the type of the colors (8-bit or 10-bit)
"

print10BitColors() {
	awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
      s="/\\";
      for (colnum = 0; colnum<term_cols; colnum++) {
          r = 255-(colnum*255/term_cols);
          g = (colnum*510/term_cols);
          b = (colnum*255/term_cols);
          if (g>255) g = 510-g;
          printf "\033[48;2;%d;%d;%dm", r,g,b;
          printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
          printf "%s\033[0m", substr(s,colnum%2+1,1);
      }
      printf "\n";
  }'
}

print8BitColors() {
	for i in {0..255}; do
		printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
		if ((i == 15)) || ((i > 15)) && (((i - 15) % 6 == 0)); then
			printf "\n"
		fi
	done
}

while test $# -gt 0; do
	case "$1" in
		-h | --help)
			echo "$help_message"
			exit 0
			;;
		-b | --bit)
			shift
			if test $# -gt 0; then
				if [ "$1" == "8" ]; then
					print8BitColors
				elif [ "$1" == "10" ]; then
					print10BitColors
				else
					echo "Invalid type specified!" && exit 1
				fi
				exit 0
			else
				echo "No type specified!"
				exit 1
			fi
			shift
			;;
		*)
			echo "$help_message"
			exit 1
			;;
	esac
done

echo "$help_message" && exit 1
