#!/bin/bash

if [ -z "$1" ]; then
  echo "Please specify an input file!" >&2
  exit 1
fi

if ! command -v code &>/dev/null; then
  echo "Please install code first!" >&2
  exit 1
fi

names=$(cat "$1")

# Split the names to form an array
SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
names=($names) # split to array $names
IFS=$SAVEIFS   # Restore IFS

for ((i = 0; i < ${#names[@]}; i++)); do
  echo "Installing ${names[$i]}..."
  code --install-extension "${names[$i]}"
done

echo "Installed all extensions successfully!"
