#!/bin/sh

# Set the encodings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set the default applications
export TERMINAL="alacritty"
export BROWSER="brave"
export EDITOR=nvim

# XDG paths
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"

# Disable less history
export LESSHISTFILE="$XDG_DATA_HOME/less/history"

# Fix some paths for programs that do not follow the XDG specs
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
# export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# Set the QT Themes
export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_STYLE_OVERRIDE=kvantum

# Ignore some commands from history
export HISTORY_IGNORE="(l|la|ll|lla|ls|cd|pwd|exit|reboot|history|cd -|cd ..|..|...|....|.....|cs|cau)"
