#!/bin/sh

# Set the encodings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set the default applications
export TERMINAL="kitty"
export BROWSER="brave"
export EDITOR=nvim

# XDG paths
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"

# Disable less history
export LESSHISTFILE="$XDG_DATA_HOME/less/history"

# Fix some paths for programs that do not follow the XDG specs
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
# export GNUPGHOME="$XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$XDG_DATA_HOME/go/bin"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PYTHONSTARTUP="$XDG_DATA_HOME/python/startup"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node/node_repl_history"
# export VIMINIT='if !has("nvim") | source "$XDG_CONFIG_HOME/vim/vimrc" | endif'

# Set the QT Themes
export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_STYLE_OVERRIDE=kvantum

# Ignore some commands from history
export HISTORY_IGNORE="(l|la|ll|lla|ls|cd|pwd|exit|reboot|history|cd -|cd ..|..|...|....|.....|vicd|cs|cau|gst|ga .|ga -u|v *|\? *|\?\? *)"

# Add Custom scripts to the path for easier access in other configs
PATH="$(find "$HOME/Scripts" -type d -printf ":%p")$PATH"

# Use my custom rofi script for asking for a password for sudo
export SUDO_ASKPASS="$HOME/Scripts/rofi/rofi-pass"

# Start the ssh-agent
eval "$(ssh-agent -s)"

# Set the profile loaded variable to use in other scripts
export PROFILE_LOADED=true
