#!/bin/sh

# Set the encodings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set the default applications
export TERMINAL="kitty"
export BROWSER="brave"
export EDITOR="nvim"
export VISUAL="nvim"

# XDG paths
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"

# Disable less history
export LESSHISTFILE="$XDG_DATA_HOME/less/history"

# Fix some paths for programs that do not follow the XDG specs
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
# export GNUPGHOME="$XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$XDG_DATA_HOME/go/bin"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PYTHONSTARTUP="$XDG_DATA_HOME/python/startup"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
# export VIMINIT='if !has("nvim") | source "$XDG_CONFIG_HOME/vim/vimrc" | endif'
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/.config/asdf/config"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="$XDG_CONFIG_HOME/asdf/tools-versions"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export ASDF_DIR="/opt/asdf-vm"

# Set the QT Themes
export QT_QPA_PLATFORMTHEME="gtk2"

# Set Python Settings
export PYTHONDONTWRITEBYTECODE=1 # tell python to not create .pyc files for the programs that were imported

# Set the default fzf options
export FZF_DEFAULT_OPTS="-i --layout=reverse --cycle --history=$XDG_DATA_HOME/fzf/history"

# Ignore some commands from history
HISTORY_IGNORE="("
#   Core utils
HISTORY_IGNORE="${HISTORY_IGNORE}l|la|ll|lla|ls|cd|pwd|exit|reboot|history"
#   CDing
HISTORY_IGNORE="$HISTORY_IGNORE|cd -|cd ..|..|...|....|.....|-"
#   Utility ->  vifm|nvim|  search
HISTORY_IGNORE="$HISTORY_IGNORE|vicd|v *|\? *|\?\? *"
#   Git
HISTORY_IGNORE="$HISTORY_IGNORE|cs|cau|gst|ga .|ga -u"
#   Golang
HISTORY_IGNORE="$HISTORY_IGNORE|gob .|goc .|gor .|got .|gov ."
HISTORY_IGNORE="$HISTORY_IGNORE)"

export HISTORY_IGNORE

# Add Custom scripts to the path for easier access in other configs
PATH="$(find "$HOME/Scripts" -type d -printf "%p:")$PATH"
PATH="$PATH:$HOME/.local/bin"
export PATH

# Use my custom rofi script for asking for a password for sudo
export SUDO_ASKPASS="$HOME/Scripts/rofi/rofi-pass"

# Start the ssh-agent
eval "$(ssh-agent -s)"

# Set the profile loaded variable to use in other scripts
export PROFILE_LOADED=true
