#!/bin/sh

# NOTE: This script also notifies the deadd-notification-center when the state of the power-saver is toggled

help_message="\
usage: power-saver [options]
  options:
    -h, --help                   Shows this help message
    --on                         Turn the power saver on
    --off                        Turn the power saver off
    --toggle                     Toggle on/off the power saver
    --screen-off                 Turn off the screen
"

set_notification_center_state() {
  # NOTE: the button has an id of 3 in the notification center(see the deadd config for more info)
  if command -v "notify-send.py" >/dev/null 2>&1; then
    notify-send.py a --hint boolean:deadd-notification-center:true \
      int:id:3 boolean:state:"$1" type:string:buttons
  fi
}

turn_on() {
  # turn on the display power saver
  # ie. turn off the display after $1 seconds or 300s (5min)

  timeout="${1:-300}"
  xset s "$timeout" "$timeout"
  xset dpms "$timeout" "$timeout" "$timeout"

  set_notification_center_state "true"
}

turn_off() {
  # turn off the display power saver
  # ie. do not turn off the display after inactivity
  xset s off off
  xset -dpms

  set_notification_center_state "false"
}

toggle() {
  is_on="$(xset q | grep 'Enabled')"

  # if it is disabled
  if [ -z "$is_on" ]; then
    # enable it
    turn_on
  else
    # disable it
    turn_off
  fi
}

turn_off_screen() {
  xset dpms force off
}

while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "$help_message"
      exit 0
      ;;
    --on)
      echo "Turning on the power-saver"
      shift
      turn_on "$1"
      exit 0
      ;;
    --off)
      echo "Turning off the power-saver"
      turn_off
      exit 0
      ;;
    --toggle)
      toggle
      exit 0
      ;;
    --screen-off)
      turn_off_screen
      exit 0
      ;;
    *)
      echo "$help_message" >&2
      exit 1
      ;;
  esac
done

echo "$help_message" >&2
exit 1
