#!/bin/sh

help_message="\
usage: power-saver [options]
  options:
    -h, --help                   Shows this help message
    --on                         Turn the power saver on
    --off                        Turn the power saver off
    --toggle                     Toggle on/off the power saver
    --screen-off                 Turn off the screen
"

turn_on() {
  # turn on the display power saver
  # ie. turn off the display after $1 seconds or 300s (5min)

  timeout="${1:-300}"
  xset s "$timeout" "$timeout"
  xset dpms "$timeout" "$timeout" "$timeout"
}

turn_off() {
  # turn off the display power saver
  # ie. do not turn off the display after inactivity
  xset s off off
  xset -dpms
}

toggle() {
  is_on="$(xset q | grep 'Enabled')"

  # if it is disabled
  if [ -z "$is_on" ]; then
    # enable it
    turn_on
  else
    # disable it
    turn_off
  fi
}

turn_off_screen() {
  # set the timeout to 1s
  turn_on 1

  # wait for the screen to turn off
  sleep 2

  # set the timeout back to on
  # NOTE: The timeout has to be turned on(only) again as if the timeout is turned off then the screen would turn on immediately
  #       It cannot be turn off
  turn_on
}

while test $# -gt 0; do
  case "$1" in
    -h | --help)
      echo "$help_message"
      exit 0
      ;;
    --on)
      echo "Turning on the power-saver"
      turn_on
      exit 0
      ;;
    --off)
      echo "Turning off the power-saver"
      turn_off
      exit 0
      ;;
    --toggle)
      toggle
      exit 0
      ;;
    --screen-off)
      turn_off_screen
      exit 0
      ;;
    *)
      echo "$help_message" >&2
      exit 1
      ;;
  esac
done

echo "$help_message" >&2
exit 1
