require("lspinstall").setup()

require("plugins.lsp.language-servers.bash")
require("plugins.lsp.language-servers.css")
require("plugins.lsp.language-servers.docker")
require("plugins.lsp.language-servers.efm")
require("plugins.lsp.language-servers.go")
require("plugins.lsp.language-servers.graphql")
require("plugins.lsp.language-servers.html")
require("plugins.lsp.language-servers.json")
require("plugins.lsp.language-servers.lua")
require("plugins.lsp.language-servers.python")
require("plugins.lsp.language-servers.typescript")
require("plugins.lsp.language-servers.vim")
require("plugins.lsp.language-servers.yaml")
