#!/bin/sh

# Set the repeat rate for keyboard
xset r rate 550 33

# Read the xresources file
xrdb "$XDG_CONFIG_HOME/X11/xresources"

# Set the compose key
setxkbmap -option 'compose:ralt'

# Run the autostart script
autostart
