require("keymappings.abbreviations")
require("keymappings.better_escape")
require("keymappings.escape")
require("keymappings.fixes")
require("keymappings.general")
-- NOTE: `lsp` keymappings are not loaded here as they are only loaded when a server is attached!
require("keymappings.misc")
require("keymappings.movements")
require("keymappings.quickfix_lists")
require("keymappings.text_objects")
