require("keymappings.abbreviations")
require("keymappings.escape")
require("keymappings.general")
require("keymappings.misc")
require("keymappings.movements")
require("keymappings.quickfix-lists")
require("keymappings.text-objects")
