#!/usr/bin/python

import argparse
from io import BytesIO
from os import popen
from subprocess import check_output
from time import sleep
from typing import Tuple

import cv2
import numpy as np
from PIL import Image

SCREENSHOT_FILEPATH = "/tmp/yt-settings-automation"
IMGS_DIR = "/".join(__file__.split("/")[:-1]) + "/imgs"
THEATRE_MODE_ICON = f"{IMGS_DIR}/theate-mode.png"
SETTINGS_ICON = f"{IMGS_DIR}/settings.png"
PLAYBACK_SPEED_ICON = f"{IMGS_DIR}/playback-speed.png"
X2_SPEED_ICON = f"{IMGS_DIR}/x2-speed.png"
PLAYER_COORDS = (450, 450)  # TODO: Try to automate this too!
SLEEP_DURATION = 0.3


def get_coords(img_path: str) -> Tuple[int, int]:
    # take a screenshot
    raw_scrot = check_output(["scrot", "-"])
    buff = BytesIO()
    buff.write(raw_scrot)
    buff.seek(0)
    scrot = Image.open(buff)

    # convert to opencv format
    scrot = np.array(scrot)
    scrot = cv2.cvtColor(scrot, cv2.COLOR_RGB2BGR)  # Convert RGB to BGR

    settings_icon = cv2.imread(img_path)
    result = cv2.matchTemplate(scrot, settings_icon, cv2.TM_CCOEFF_NORMED)
    y, x = np.unravel_index(result.argmax(), result.shape)
    y, x = y + 15, x + 15  # move to the center of the match
    return (x, y)


def move_cursor(x: int, y: int) -> None:
    popen(f"xdotool mousemove {x} {y}")


def click() -> None:
    popen("xdotool click 1")


parser = argparse.ArgumentParser()
parser.add_argument(
    "what",
    help="What to set?",
    type=str,
    choices=["theatre-mode", "x2-speed"],
)
args = parser.parse_args()

actions = []
match args.what:
    case "theatre-mode":
        actions.append(THEATRE_MODE_ICON)
    case "x2-speed":
        actions.append(SETTINGS_ICON)
        actions.append(PLAYBACK_SPEED_ICON)
        actions.append(X2_SPEED_ICON)

# move mouse to a location on the player
move_cursor(*PLAYER_COORDS)

for item in actions:
    # Click the settings icon
    sleep(SLEEP_DURATION)  # wait for the mouse to move
    move_cursor(*get_coords(item))
    sleep(SLEEP_DURATION)  # wait for the mouse to move
    click()
    sleep(SLEEP_DURATION)  # wait for the mouse to click


# Click anywhere else on the player to hide the settings menu
if args.what != "theatre-mode":
    move_cursor(*PLAYER_COORDS)
    sleep(SLEEP_DURATION)  # wait for the mouse to move
    click()
