#!/bin/bash

declare -A options
options[ alacritty]="$HOME/.config/alacritty/alacritty.yml"
options[ awesome]="$HOME/.config/awesome/rc.lua"
options[ bash]="$HOME/.config/bash/init.bash"
options[ bashrc]="$HOME/.bashrc"
options[ bash_profile]="$HOME/.bash_profile"
options[ deadd-notification-center]="$HOME/.config/deadd/deadd.yml"
options[ doom]="$HOME/.config/doom/config.el"
options[ fontconfig]="$HOME/.config/fontconfig/fonts.conf"
options[ git]="$HOME/.config/git/config"
options[ hyprland]="$HOME/.config/hypr/hyprland.conf"
options[ i3]="$HOME/.config/i3/config"
options[ kitty]="$HOME/.config/kitty/kitty.conf"
options[ lynx]="$HOME/.config/lynx/lynx.cfg"
options[ mpv]="$HOME/.config/mpv/mpv.conf"
options[ neofetch]="$HOME/.config/neofetch/config.conf"
options[ nvim]="$HOME/.config/nvim/init.lua"
options[ pacwall]="$HOME/.config/pacwall/pacwall.conf"
options[ picom]="$HOME/.config/picom/picom.conf"
options[ polybar]="$HOME/.config/polybar/config.ini"
options[ qtile]="$HOME/.config/qtile/config.py"
options[ rofi]="$HOME/.config/rofi/config.rasi"
options[ shell]="$HOME/.config/shell/init.sh"
options[ sxhkd]="$HOME/.config/sxhkd/sxhkdrc"
options[節tmux]="$HOME/.config/tmux/tmux.conf"
options[ vifm]="$HOME/.config/vifm/vifmrc"
options[ vim]="$HOME/.config/vim/vimrc"
options[ vimiv]="$HOME/.config/vimiv/vimiv.conf"
options[ X11]="$HOME/.config/X11/xprofile"
options[ xplr]="$HOME/.config/xplr/init.lua"
options[牢 zathura]="$HOME/.config/zathura/zathurarc"
options[ zsh]="$HOME/.config/zsh/init.zsh"

edit_file() {
  selected_config_path=$(printf '%s\n' "${options[$1]}")
  selected_config_dir="${selected_config_path%/*}"

  cd "$selected_config_dir" || exit 1

  # if [ -t 0 ]; then
  #   exec nvim "$selected_config_path"
  # else
  #   exec $TERMINAL -e nvim "$selected_config_path"
  # fi
  exec $TERMINAL -e nvim "$selected_config_path"
}

# if a name has been specified, directly edit it
if [ -n "$1" ]; then
  # edit_file "${options[$1]}"
  actual_name="$(echo "${!options[@]}" | grep -E -o ". $1")"
  [ -z "$actual_name" ] && echo "This config does not exist!" && exit 1
  edit_file "$actual_name"
fi

selected_config_name=""

# if [ -t 0 ]; then
#   config_names=""
#   for config in "${!options[@]}"; do
#     if [[ -z $config_names ]]; then
#       config_names="$config"
#     else
#       config_names="$config_names
# $config"
#     fi
#   done
#   selected_config_name="$(echo "$config_names" | fzf --prompt 'Select a config: ')"
# else
#   marked_up_config_names=""
#   for config in "${!options[@]}"; do
#     config_name="$config"
#     config_path=${options[$config]}

#     marked_up_config_name="$config_name <span font_size='smaller' font_weight='light' style='italic'>(${config_path//\/home\/$USER/\~})</span>"

#     if [[ -z $marked_up_config_names ]]; then
#       marked_up_config_names="$marked_up_config_name"
#     else
#       marked_up_config_names="$marked_up_config_names
# $marked_up_config_name"
#     fi
#   done

#   selected_config_name=$(echo "$marked_up_config_names" | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -markup-rows -dmenu -i -p "Edit config")
#   selected_config_name="${selected_config_name%% <span*}"
# fi

marked_up_config_names=""
for config in "${!options[@]}"; do
  config_name="$config"
  config_path=${options[$config]}

  marked_up_config_name="$config_name <span font_size='smaller' font_weight='light' style='italic'>(${config_path//\/home\/$USER/\~})</span>"

  if [[ -z $marked_up_config_names ]]; then
    marked_up_config_names="$marked_up_config_name"
  else
    marked_up_config_names="$marked_up_config_names
$marked_up_config_name"
  fi
done

selected_config_name=$(echo "$marked_up_config_names" | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -markup-rows -dmenu -i -p "Edit config")
selected_config_name="${selected_config_name%% <span*}"

[[ -z $selected_config_name ]] && exit 0

# What to do when/if we choose a file to edit.
edit_file "$selected_config_name"
