#!/usr/bin/env bash

declare -A options
options[ alacritty]="$HOME/.config/alacritty/alacritty.yml"
options[ bash]="$HOME/.config/bash/init_bash.bash"
options[ bashrc]="$HOME/.bashrc"
options[ bash_profile]="$HOME/.bash_profile"
options[ doom]="$HOME/.config/doom/config.el"
options[ fontconfig]="$HOME/.config/fontconfig/fonts.conf"
options[ git]="$HOME/.config/git/config"
options[ i3]="$HOME/.config/i3/config"
options[ mpv]="$HOME/.config/mpv/mpv.conf"
options[ neofetch]="$HOME/.config/neofetch/config.conf"
options[ nvim]="$HOME/.config/nvim/init.lua"
options[ pacwall]="$HOME/.config/pacwall/pacwall.conf"
options[ picom]="$HOME/.config/picom/picom.conf"
options[ polybar]="$HOME/.config/polybar/config.ini"
options[ qtile]="$HOME/.config/qtile/config.py"
options[ rofi]="$HOME/.config/rofi/config.rasi"
options[ shell]="$HOME/.config/shell/init_shell.sh"
options[ sxhkd]="$HOME/.config/sxhkd/sxhkdrc"
options[節tmux]="$HOME/.tmux.conf"
options[ vifm]="$HOME/.config/vifm/vifmrc"
options[ vim]="$HOME/.config/vim/vimrc"
options[ vimiv]="$HOME/.config/vimiv/vimiv.conf"
options[ X11]="$HOME/.config/X11/xprofile"
options[牢 zathura]="$HOME/.config/zathura/zathurarc"
options[ zsh]="$HOME/.config/zsh/init_zsh.zsh"

selected_config_name=$(printf '%s\n' "${!options[@]}" | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -dmenu -i -p "Edit config:")

[ -z "$selected_config_name" ] && exit 0

# What to do when/if we choose a file to edit.
selected_config_path=$(printf '%s\n' "${options["$selected_config_name"]}")
selected_config_dir="${selected_config_path%/*}"

cd "$selected_config_dir" || exit 1

rofi-sensible-terminal -e nvim "$selected_config_path" &
