#!/bin/sh

# Get all the available scripts
available_scripts=$(find "$HOME/Scripts" -type f | sed "s+$HOME/Scripts/++g")

# Let the user select the script through rofi
selected_script="$(echo "$available_scripts" | sort | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -dmenu -p "Edit a script:")"

# Check if the user selected any config
[ -z "$selected_script" ] && exit 0

cd "$HOME/Scripts" || exit 1
rofi-sensible-terminal -e nvim "$HOME/Scripts/$selected_script" &
