#!/bin/bash

error_message() {
  rofi -theme "$HOME/.config/rofi/themes/message.rasi" -e " $1"
  exit 1
}

if ! command -v playerctl >/dev/null 2>&1; then
  error_message "playerctl is not installed!"
fi

# Check if spotify is running
if ! playerctl metadata >/dev/null 2>&1; then
  error_message "No player is running!"
fi

# Find the current playing song
current_info="$(playerctl metadata --format "<span font_size='small' font_weight='light' style='italic'>{{ uc(playerName) }}</span>
<span font_size='larger' font_weight='bold'>{{ title }}</span> <span font_size='smaller' style='italic'>by {{ artist }}</span>")"

# Options
previous="玲"
playpuase="懶"
next="怜"

# Variable passed to rofi
options="$previous|$playpuase|$next"

selected="$(echo "$options" | rofi -markup -selected-row 1 -sep "|" -dmenu -i -mesg "$current_info" -theme "$HOME/.config/rofi/themes/media-control.rasi")"

case "$selected" in
  "$playpuase") playerctl play-pause ;;
  "$previous") playerctl previous ;;
  "$next") playerctl next ;;
esac
