#!/bin/bash

MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System :' \
-lines 4 \
-line-padding 10 \
-padding 20 \
-width 15 \
-xoffset -10 -yoffset 40 \
-location 3 \
<<< " Lock| Logout| Reboot| Shutdown")"
case "$MENU" in
  *Lock) dm-tool lock;;
  *Logout) sudo /etc/init.d/gdm3 restart;;
  *Reboot) reboot ;;
  *Shutdown) shutdown now
esac

