#!/bin/bash

# Find the uptime of the machine
uptime=$(uptime -p | sed -e 's/up //g')

# Options (using Feather fonts)
lock=""
logout=""
sleep=""
reboot=""
shutdown=""

# Variable passed to rofi
options="$lock|$logout|$sleep|$reboot|$shutdown"

selected="$(rofi -no-lazy-grab -selected-row 2 -sep "|" -dmenu -i -p "Uptime :  $uptime" \
-theme "$HOME/.config/rofi/themes/power_menu.rasi" \
<<< "$options")"

case "$selected" in
  $lock) dm-tool lock ;;
  $logout) sudo /etc/init.d/gdm3 restart ;;
  $sleep) sudo pm-suspend ;;
  $reboot) reboot ;;
  $shutdown) shutdown now
esac

