#!/bin/sh

# Get all the available scripts
available_scripts=$(find "$HOME/Scripts" -type f | sed "s+$HOME/Scripts/++g")

# Let the user select the script through rofi
selected_script="$(echo "$available_scripts" | sort | rofi -dmenu -p "Run a script: ")"

# Check if the user selected any config
[ -z "$selected_script" ] && echo "Cancel" && exit 0

sh -c "$HOME/Scripts/$selected_script"
