#!/bin/sh

SESSIONNAME="auth-backend"

cd "$HOME/Repos/github.com/sethigeet/gql-go-auth-backend" || exit 1

# Check if the session already exists
if ! tmux has-session -t $SESSIONNAME >/dev/null 2>&1; then
  tmux new-session -s $SESSIONNAME -n "git" -d
  tmux send-keys -t $SESSIONNAME "gst" C-m

  tmux new-window -n "code"
  tmux send-keys -t $SESSIONNAME "v main.go" C-m

  tmux new-window -n "run"
  tmux send-keys -t $SESSIONNAME "go run ."

  tmux new-window -n "search"
  tmux send-keys -t $SESSIONNAME "? "

  # tmux split-window -h

  tmux new-window -n "docker"
  tmux send-keys -t $SESSIONNAME "docker start postgres redis"
fi

if [ -t 0 ]; then
  exec tmux attach -t $SESSIONNAME
else
  exec $TERMINAL -e tmux attach -t $SESSIONNAME
fi
