-- General (requires nerd-font)
-- local icons = {
--   Class = "  ",
--   Color = "  ",
--   Constant = " ﲀ ",
--   Constructor = "  ",
--   Enum = " 練 ",
--   EnumMember = "  ",
--   Event = "  ",
--   Field = " ﴲ ",
--   File = "  ",
--   Folder = "  ",
--   Function = "  ",
--   Interface = " ﰮ ",
--   Keyword = "  ",
--   Method = "  ",
--   Module = "  ",
--   Operator = " ",
--   Property = " 襁 ",
--   Reference = "  ",
--   Snippet = "  ",
--   Struct = "  ",
--   Text = "  ",
--   TypeParameter = "  ",
--   Unit = " 塞",
--   Value = "  ",
--   Variable = "[]",
-- }

-- VSCode Style (requires codicon font)
local icons = {
  Array = "",
  Boolean = "",
  Calendar = "",
  Character = "",
  Class = "",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  Function = "",
  Interface = "",
  Key = "",
  Keyword = "",
  Method = "",
  Module = "",
  Namespace = " ",
  Null = "",
  Number = "",
  Object = "",
  Operator = "",
  Package = "",
  Parameter = "",
  Property = "",
  Reference = "",
  Snippet = "",
  String = "",
  Struct = "",
  Table = "",
  Tag = " ",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
  Watch = " ",
}

return icons
