-- General (requires nerd-font)
-- local icons = {
--   Class = "  ",
--   Color = "  ",
--   Constant = " ﲀ ",
--   Constructor = "  ",
--   Enum = " 練 ",
--   EnumMember = "  ",
--   Event = "  ",
--   Field = " ﴲ ",
--   File = "  ",
--   Folder = "  ",
--   Function = "  ",
--   Interface = " ﰮ ",
--   Keyword = "  ",
--   Method = "  ",
--   Module = "  ",
--   Operator = " ",
--   Property = " 襁 ",
--   Reference = "  ",
--   Snippet = "  ",
--   Struct = "  ",
--   Text = "  ",
--   TypeParameter = "  ",
--   Unit = " 塞",
--   Value = "  ",
--   Variable = "[]",
-- }

-- VSCode Style (requires codicon font)
local icons = {
  Text = "  ",
  Method = "  ",
  Function = "  ",
  Constructor = "  ",
  Field = "  ",
  Variable = "  ",
  Class = "  ",
  Interface = "  ",
  Module = "  ",
  Property = "  ",
  Unit = "  ",
  Value = "  ",
  Enum = "  ",
  Keyword = "  ",
  Snippet = "  ",
  Color = "  ",
  File = "  ",
  Reference = "  ",
  Folder = "  ",
  EnumMember = "  ",
  Constant = "  ",
  Struct = "  ",
  Event = "  ",
  Operator = "  ",
  TypeParameter = "  ",
}

return icons
