#!/bin/sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=secrets &
picom &
set-background -r &
playerctld daemon &
greenclip daemon &
sxhkd &
nm-applet --indicator & # Only for wifi enabled computers
blueman-applet &        # Only for bluetooth enabled computers
notification-ctl restart &
power-saver --on &
