#!/bin/sh

gnome-keyring-daemon --start --components=secrets &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
set-background -r &
playerctld daemon &
greenclip daemon &
nm-applet --indicator & # Only for wifi enabled computers
gammastep -O 4500 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP          # for XDPH
