#!/usr/bin/env bash

# This script requires notify-send.sh to send notifications

help_message="\
usage: volume-control subcommand [options]
  options:
    help                         Shows this help message
    up [amount]                  Increases the volume by the specified amount or the default amount
    down [amount]                Decreases the volume by the specified amount or the default amount
    mute                         Mutes the volume
"

notify_error() {
  notify-send.sh -u low -r 15 "Install alsa-utils!"
  exit 1
}

command -v "amixer" &>/dev/null || notify_error

check_mute() { amixer get Master | grep 'off'; }

notify() {
  VOLUME="$(amixer get Master | grep -oP '\[\K[^%\]]+' | head -n1)"

  if [[ $VOLUME -eq 0 ]]; then
    icon_name="audio-volume-muted"
  elif [[ $VOLUME -lt 10 ]]; then
    icon_name="audio-volume-low"
  elif [[ $VOLUME -lt 30 ]]; then
    icon_name="audio-volume-low"
  elif [[ $VOLUME -lt 70 ]]; then
    icon_name="audio-volume-medium"
  else
    icon_name="audio-volume-high"
  fi

  notify-send.sh -i "$icon_name" -t 700 -r 123 "$VOLUME% " -h int:value:"$VOLUME"
}

case $1 in
  up)
    shift
    amixer set Master on -q
    amixer sset Master "${1:-5}"%+ -q
    notify
    ;;
  down)
    shift
    amixer set Master on -q
    amixer sset Master "${1:-5}"%- -q
    notify
    ;;
  mute)
    amixer set Master 1+ toggle -q
    if check_mute &>/dev/null; then
      icon_name="notification-audio-volume-muted"
      notify-send.sh -i "$icon_name" -t 700 -r 123 "Muted "
    else
      notify
    fi
    ;;
  help)
    echo "$help_message"
    exit 0
    ;;
  *)
    echo "$help_message"
    exit 1
    ;;
esac
